# -*- coding: utf-8 -*-
"""ML 349 - Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d0U9Llp3l-aLDjiaiqf7JevMTe3uW_MW
"""

import re

"""## Read data"""

lines = []
with open('wiki.test.dot', "r") as f:
  lines = f.readlines()

print(len(lines))

"""## Pre-processing"""

def extractWord(line):
    # -- Remove punctuation
    line = re.sub(r'[^\w\s]', '', line)
    # -- Split into words by space
    words = line.split(' ')
    # -- Remove characters
    regex_pattern = r'([^a-zA-Z ]+?)'
    words = [re.sub(regex_pattern, '', x) for x in words]
    for word in words:
        if len(word) < 2 :
            words.remove(word)
    # -- Remove capitalization
    words = [x.lower() for x in words]

    return words

prcoessed_lines = []
words = []
for line in lines:
    if len(line) < 4:
        lines.remove(line)
    else:
        words += extractWord(line)
print('len of lines:', len(lines))
print('number of words:', len(words))
print('examples of processed words:', words[9:20])



"""**NEURAL NETWORK APPROACH**"""

# load doc into memory
def load_doc(filename):
	# open the file as read only
	file = open(filename, 'r')
	# read all text
	text = file.read()
	# close the file
	file.close()
	return text

# load document
in_filename = 'wiki.train.dot'
doc = load_doc(in_filename)
print(doc[:200])

import string
 
# turn a doc into clean tokens
def clean_doc(doc):
	# replace '--' with a space ' '
  doc = doc.replace('--', ' ')
  #replace <unk> with a space
  doc = doc.replace('<unk>', ' ')
	# split into tokens by white space
  tokens = doc.split()
	# remove punctuation from each token
  table = str.maketrans('', '', string.punctuation)
  tokens = [w.translate(table) for w in tokens]
	# remove remaining tokens that are not alphabetic
  tokens = [word for word in tokens if word.isalpha()]
	# make lower case
  tokens = [word.lower() for word in tokens]
  #removing stopwords
  return tokens

# clean document
tokens = clean_doc(doc)
print(tokens[:200])
print('Total Tokens: %d' % len(tokens))
print('Unique Tokens: %d' % len(set(tokens)))

# organize into sequences of tokens
length = 50 + 1
sequences = list()
for i in range(length, len(tokens)):
	# select sequence of tokens
	seq = tokens[i-length:i]
	# convert into a line
	line = ' '.join(seq)
	# store
	sequences.append(line)
print('Total Sequences: %d' % len(sequences))

# save tokens to file, one dialog per line
def save_doc(lines, filename):
	data = '\n'.join(lines)
	file = open(filename, 'w')
	file.write(data)
	file.close()

# save sequences to file
out_filename = 'wiki_train_sequences.txt'
save_doc(sequences, out_filename)

#Training the model

# load doc into memory
def load_doc(filename):
	# open the file as read only
	file = open(filename, 'r')
	# read all text
	text = file.read()
	# close the file
	file.close()
	return text
 
# load
in_filename = 'wiki_train_sequences.txt'
doc = load_doc(in_filename)
lines = doc.split('\n')

# integer encode sequences of words
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)
sequences = tokenizer.texts_to_sequences(lines)

# vocabulary size
vocab_size = len(tokenizer.word_index) + 1

# separate into input and output
import numpy as np
from tensorflow.keras.utils import to_categorical
sequences = np.array(sequences)
X, y = sequences[:,:-1], sequences[:,-1]
y = to_categorical(y, num_classes=vocab_size)
seq_length = X.shape[1]


# define model
from keras.layers import LSTM, Dense, Embedding
from keras.models import Sequential
model = Sequential()
model.add(Embedding(vocab_size, 50, input_length=seq_length))
model.add(LSTM(100, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())


# compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit model
model.fit(X, y, batch_size=128, epochs=100)


# save the model to file
from pickle import dump
model.save('model.h5')
# save the tokenizer
dump(tokenizer, open('tokenizer.pkl', 'wb'))

#using language model
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences


# load doc into memory
def load_doc(filename):
    # open the file as read only
    file = open(filename, 'r')
    # read all text
    text = file.read()
    # close the file
    file.close()
    return text


# generate a sequence from a language model
def generate_seq(model, tokenizer, seq_length, seed_text, n_words):
    result = list()
    in_text = seed_text
    # generate a fixed number of words
    for _ in range(n_words):
        # encode the text as integer
        encoded = tokenizer.texts_to_sequences([in_text])[0]
        # truncate sequences to a fixed length
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        # predict probabilities for each word
        yhat = model.predict_classes(encoded, verbose=0)
        # map predicted word index to word
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
        # append to input
        in_text += ' ' + out_word
        result.append(out_word)
    return ' '.join(result)


# load cleaned text sequences
in_filename = 'wiki_train_sequences.txt'
doc = load_doc(in_filename)
lines = doc.split('\n')
seq_length = len(lines[0].split()) - 1

# load the model
model = load_model('model.h5')

# load the tokenizer
tokenizer = load(open('tokenizer.pkl', 'rb'))

# select a seed text
from random import randint
seed_text = lines[randint(0, len(lines))]
print(seed_text + '\n')

# generate new text
generated = generate_seq(model, tokenizer, seq_length, seed_text, 50)
print(generated)

###TEMPORARY ENDING
